# （必填）请指定管理员的微信ID（不允许填写本账号）
## 如果有多个，请用逗号分割
admin = '请指定您的WXID'

[datasource]
type = "postgres"
host = "127.0.0.1"
port = 5432
schema = "public"
username = "postgres"
password = "postgres"
database = "wechat_bot"

# 节假日 API 配置
[holiday]
api = 'https://api.apihubs.cn/holiday/get'
param = { holiday_recess = 1, cn = 1, size = 50 }